# Generated by Django 4.2.1 on 2023-05-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукция', 'verbose_name_plural': 'Продукции'},
        ),
        migrations.AlterField(
            model_name='factory',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='factory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='product',
        ),
        migrations.RemoveField(
            model_name='retail',
            name='product',
        ),
        migrations.AddField(
            model_name='factory',
            name='product',
            field=models.ManyToManyField(to='network_links.product'),
        ),
        migrations.AddField(
            model_name='individual',
            name='product',
            field=models.ManyToManyField(to='network_links.product'),
        ),
        migrations.AddField(
            model_name='retail',
            name='product',
            field=models.ManyToManyField(to='network_links.product'),
        ),
    ]
