# Generated by Django 4.2.1 on 2023-06-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_links', '0004_contacts_network_remove_individual_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name': 'Звено сети', 'verbose_name_plural': 'Звенья сети'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукция', 'verbose_name_plural': 'Продукция'},
        ),
        migrations.RemoveField(
            model_name='network',
            name='number_house',
        ),
    ]
